### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by miltonlab** [giticUNL/giticUNL.github.io#1]
@edisoncor wich is the file and line to change the background color of Objetives section ?

**Comment by edisoncor** [comment]
Is in  [main.css](https://github.com/giticUNL/giticUNL.github.io/blob/master/assets/css/main.css) the color defition is in line 8, 9, 10, 11

Ref: [pallete](http://www.colourlovers.com/palette/130451/Tis_the_Season)
